name: Driven_CD
on:
  push:
    branch: [main]
jobs:
  deploy:
    name: Deploy new version
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Set up Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Migrate DB to new version
        run: goose -dir "sql/schema" postgres "${{ secrets.DB_URL }}" up
