// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full bg-flame-bg h-screen\"><div class=\"bg-flame-bg flex justify-center w-full text-flame-text\"><div class=\"w-64 m-3 bg-flame-surface p-6 h-90 rounded flex flex-col gap-4\"><h2 class=\"text-lg font-bold text-center\">New tasks</h2><div class=\"p-3 border gap-1 border-flame-accent rounded\"><label class=\"block text-sm\">Day:</label> <input type=\"text\" class=\"w-full p-1 bg-gray-700 rounded text-white\"> <label class=\"block text-sm mt-2\">Task:</label> <input type=\"text\" class=\"w-full p-1 bg-gray-700 rounded text-white\"> <label class=\"block text-sm mt-2\">Keys:</label> <input type=\"text\" class=\"w-full p-1 bg-gray-700 rounded text-white\"></div><button class=\"bg-flame-primary hover:bg-flame-hover cursor-pointer text-white py-2 px-4 rounded\">Add Task</button></div><div class=\"w-full\" id=\"view\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
