// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePageScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script type=\"text/javascript\">\n\t\tdocument.addEventListener(\"DOMContentLoaded\", (e) => {\n\t\t    document.addEventListener(\"htmx:beforeSwap\", (event) => {\n\t\t\t\tif (event.detail.xhr.status == 403) {\n\t\t\t     event.detail.shouldSwap = true;\n\t\t\t\t} else if (event.detail.target == document.querySelector(\"#task-form-msg\")\n\t\t\t\t  && event.detail.xhr.status == 201) { // creat task success\n\t\t\t\t\tevent.detail.shouldSwap = false;\n\t\t\t\t}\n\t\t\t});\n\n\t\t\t// function scrollToBigTask(taskID) {\n\t\t\t//     const taskElement = document.getElementById(taskID);\n\t\t\t// \tif (taskElement) {\n\t\t\t// \t   taskElement.scrollIntoView({ behavior: \"smooth\" });\n\t\t\t// \t}\n\t\t\t// }\n\n\t\t\t// document.addEventListener(\"scrollToTask\", (event) => {\n\t\t\t//    scrollToBigTask(event.detail.value);\n\t\t\t// });\n\t\t});\n\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
