// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LandingPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"min-h-screen flex flex-col justify-center bg-flame-bg gap-3\"><img src=\"/static/img/driven_logo.png\" width=\"500\" class=\"mx-auto mt-10\"><!-- Hero section --><section class=\"flex flex-col items-center justify-center text-center px-6 pt-6 pb-14\"><h2 class=\"text-4xl md:text-5xl font-extrabold mb-4 text-flame-primary\">A To-do List for Grinders</h2><ul class=\"text-lg text-flame-muted max-w-2xl mb-10\"><li>⚡ Built with Go + HTMX for full SSR & blazing-fast performance.</li><li>🔐 Secure access token framework for a smooth experience.</li><li>🎯 Designed for students who want to stay in flow and crush their goals.</li></ul><a href=\"/signup\" class=\"px-8 py-3 rounded-lg bg-flame-primary text-flame-bg text-lg font-semibold hover:bg-flame-hover transition\">Get Started</a></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
