// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func signUpForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen flex items-center justify-center\"><form id=\"form\" hx-post=\"/signup\" hx-target=\"#alert\" class=\"bg-flame-surface shadow-lg rounded-lg p-8 w-full max-w-md flex flex-col space-y-6\"><h2 class=\"text-2xl font-bold text-center text-flame-text\">Register</h2><div class=\"flex flex-col\"><label for=\"name\" class=\"mb-2 text-gray-300\">Name</label> <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Enter your name\" class=\"border border-gray-600 rounded-md p-2 bg-gray-700 text-flame-text focus:outline-none focus:ring-2 focus:ring-flame-primary\"></div><div class=\"flex flex-col\"><label for=\"email\" class=\"mb-2 text-gray-300\">Email</label> <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your email\" class=\"border border-gray-600 rounded-md p-2 bg-gray-700 text-flame-text focus:outline-none focus:ring-2 focus:ring-flame-primary\"><p class=\"text-red-500\" id=\"alert\"></p></div><div class=\"flex flex-col\"><label for=\"password\" class=\"mb-2 text-gray-300\">Password</label> <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" class=\"border border-gray-600 rounded-md p-2 bg-gray-700 text-flame-text focus:outline-none focus:ring-2 focus:ring-flame-primary\"></div><button type=\"submit\" class=\"bg-blue-700 hover:bg-blue-800 disabled:bg-grey-800 cursor-pointer text-flame-text font-semibold py-2 rounded-md transition-colors\" hx-disabled-elt=\"this\">Sign Up</button><p class=\"text-center text-gray-400 text-sm\">Already have an account? <a href=\"/signin\" class=\"text-blue-400 hover:underline\">Sign In</a></p></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SignUpPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<main class=\"w-screen h-full bg-flame-bg\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = signUpForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
