name: Driven_CD
on:
  push:
    branches: [main]
env:
  GOOSE_DRIVER: postgres
  GOOSE_MIGRATION_DIR: sql/schema
  GOOSE_DBSTRING: ${{ secrets.DB_URL }}
jobs:
  deploy:
    name: Deploy new version
    runs-on: ubuntu-latest # have docker and aws installed

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Set up Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Migrate DB to new version
        run: goose up
      - name: Build product
        run: go build -o driven cmd/main.go

      - name: Auth Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Build Docker image and push to GCP AR
        run: gcloud builds submit --tag northamerica-northeast2-docker.pkg.dev/driven-458703/driven-registry:latest .
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy notely
          --image northamerica-northeast2-docker.pkg.dev/driven-458703/driven-registry:latest
          --region northamerica-northeast2
          --allow-unauthenticated
          --project driven-458703
          --max-instances=4
