name: Driven_CD
on:
  push:
    branches: [main]
env:
  GOOSE_DRIVER: postgres
  GOOSE_MIGRATION_DIR: sql/schema
  GOOSE_DBSTRING: ${{ secrets.DB_URL }}
jobs:
  deploy:
    name: Deploy new version
    runs-on: ubuntu-latest # have docker and aws installed

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Set up Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Migrate DB to new version
        run: goose up
      - name: Build product
        run: go build -o driven cmd/main.go
      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ECR_REGION }}
      - name: Login to ECR
        run: >
          aws ecr get-login-password
          --region ${{ secrets.ECR_REGION }} | docker login
          --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      - name: Build container
        run: docker build -t driven .
      - name: Tag image
        run: docker tag driven:latest ${{ secrets.ECR_REGISTRY }}/driven:latest
      - name: Push image
        run: docker push ${{ secrets.ECR_REGISTRY }}/driven:latest
